variable "env" {
  type        = string
  description = "environment name"
}

variable "region" {
  type        = string
  description = "AWS region"
}

variable "ecs_cluster_name" {
  type        = string
  description = "ECS cluster name"
}

variable "ecs_service_name" {
  type        = string
  description = "ECS service name"
}

variable "devops_agent_ingestion_lambda" {
  type        = string
  default     = "devops-agent-ingestion"
  description = "The name of the DevOps Agent webhook for the ingestion Lambda function"
}

variable "enable_devops_agent_integration" {
  type        = bool
  default     = false
  description = "Toggled to true after completing AWS DevOps Agent onboarding on the web console"
}

variable "devops_agent_webhook_url" {
  type        = string
  description = "Webhook URL generated by AWS DevOps Agent"
}

variable "devops_agent_api_key" {
  type        = string
  sensitive   = true
  description = "API Key generated by AWS DevOps Agent"
}

variable "slack_workspace_id" {
  type        = string
  default     = ""
  description = "Slack workspace/team ID for Amazon Q Chatbot (optional; leave empty to configure channel in console)"
}

variable "slack_channel_id" {
  type        = string
  default     = ""
  description = "Slack channel ID for ops alarms (optional; leave empty to configure channel in console)"
}
