name: 2-terraform-plan
on:
    pull_request:
        branches: ["main"]
        paths: ["terraform/**", ".github/workflows/terraform-plan.yml"]
    workflow_dispatch:
        inputs:
            environment:
                description: "TARGET ENVIRONMENT"
                required: true
                type: choice
                default: "dev"
                options:
                    - dev
                    - prod

permissions:
    id-token: write
    contents: read

env:
    AWS_REGION: "eu-west-2"
    AWS_ROLE_NAME: "arn:aws:iam::774667856934:role/github-actions-tf-plan-role"
    TF_WORK_DIR: "terraform/environments/${{ github.event.inputs.environment || 'dev' }}"

jobs:
    validate-and-plan:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4

            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.7.0"

            - name: "Code Formatting Check"
              run: terraform fmt -check -recursive
              working-directory: terraform

            - name: "Initialize Workspace Configuration"
              run: terraform init -backend=false
              working-directory: ${{ env.TF_WORK_DIR }}

            - name: "Validate Syntax Integrity"
              run: terraform validate
              working-directory: ${{ env.TF_WORK_DIR }}

            - name: "Setup TFLint Environment"
              uses: terraform-linters/setup-tflint@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: "TF-lint Analysis"
              run: |
                  tflint --init
                  tflint -f compact
              working-directory: ${{ env.TF_WORK_DIR }}

            - name: "Checkov Scan"
              uses: bridgecrewio/checkov-action@master
              with:
                  framework: terraform
                  output_format: cli
                  soft_fail: true
                  skip_check: "CKV_AWS_111,CKV_AWS_135,CKV_AWS_158,CKV2_AWS_6,CKV_AWS_18,CKV_AWS_19,CKV_AWS_144,CKV_AWS_145"

            - name: "COnfigure AWS Via OIDC"
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ env.AWS_ROLE_NAME }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: "Generate DRY Run Infrastrucuture Plan"
              run: |
                  terraform init
                  terraform plan -input=false
              working-directory: ${{ env.TF_WORK_DIR }}
